Email changed to Username
transkript/ireportcard-client pull request #74
Opened 2022-09-03 20:13 UTC by mofirojean

### Contributor Checklist

Fixes #71

- [ ] Did you add comments for every public function/method?
- [ ] Did you specify the type of improvement?
- [ ] Did you request a desired merge strategy?

#### Type of Improvement

- documentation

#### Backend Code Generation Impact

- NAN

#### Desired Merge Strategy

- Squash

#### Release Notes

-

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?

2022-09-08 08:17 UTC, elroykanye reviewed
Thanks

2022-09-08 08:17 UTC, elroykanye commented on src/app/modules/rc-auth/components/login/login.component.html
> +  <label for="email" class="block text-900 font-medium mb-2">Username</label>
This will be better as `Email/Username`

2022-09-08 08:18 UTC, elroykanye requested changes

2022-09-08 15:07 UTC, mofirojean commented on src/app/modules/rc-auth/components/login/login.component.html
> +  <label for="email" class="block text-900 font-medium mb-2">Username</label>
I just corrected it

2022-09-08 15:12 UTC, mofirojean commented
Hey @elroykanye 
i have changed the name as you required 

but what about the formControlName in the code below
<input id="email" type="text" pInputText class="w-full mb-3" [formControlName]="'username'"

2022-09-08 15:35 UTC, elroykanye commented
It is not an issue and does not relate to this fix. Let us keep fixes specific, as anything changing about form control name with break the functionality of the form and consequent request body sent to the backend.

2022-09-08 18:46 UTC, mofirojean commented
Ok Thanks for the clarification

2022-09-08 18:47 UTC, mofirojean commented
waiting for you to merge

2022-09-09 16:26 UTC, mofirojean commented on src/app/modules/rc-auth/components/login/login.component.html
> +  <label for="email" class="block text-900 font-medium mb-2">Username</label>
Ok let me get to it

2022-10-19 21:41 UTC, elroykanye approved these changes

2022-10-19 21:41 UTC, merged